name: "Deployment"
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  transfer:
    name: Transfer files to Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Deploy Files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          server: ${{ secrets.SSH_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./*"
          remote_path: "/home/github/escape"
          sftpArgs: "-o ConnectTimeout=5"
  deploy:
    name: Start docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/github/escape
            docker build -t escape .
            docker stop escape-container
            docker start --name escape-container -p 3031:3000 -d escape:latest
